### ISSUE TITLE
Missing MQTTPingTask

### ISSUE THREAD

**Issue by armel-31** [jondurrant/RPIPicoRTOSMQTT#1]
Compiling the project, it seems MQTTPingTask class is missing (.h/.c) :

```
[ 69%] Building CXX object src/CMakeFiles/PicoMQTT.dir/main.cpp.obj
In file included from /home/armel/Coding/RaspberryPico/RPIPicoRTOSMQTT/src/main.cpp:8:0:
/home/armel/Coding/RaspberryPico/RPIPicoRTOSMQTT/src/MQTTRouterPing.h:14:10: fatal error: MQTTPingTask.h: No such file or directory
 #include "MQTTPingTask.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/PicoMQTT.dir/build.make:63: src/CMakeFiles/PicoMQTT.dir/main.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1742: src/CMakeFiles/PicoMQTT.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

_I've removed the class in the cmake for information_

**Comment by jondurrant** [comment]
Sorry about that.  I will upload tomorrow.

Jon

**Comment by jondurrant** [comment]
Uploaded the file. Sorry about that.

Though I have noticed that this isn't very stable with high volumes of messages. I tried an alterative version at https://github.com/jondurrant/RPIPicoRTOSMQTT3 which is more stable.

**Comment by armel-31** [comment]
No problem, thank you for the update, you are doing a great job
